owner: SDS1337 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: 'Flixari'
    url: https://flixari.co
    icon: https://assets.flixari.co/organizr/logo.png
    expectedStatusCodes:
      - 200
    maxRedirects: 0
  - name: Hermes
    url: https://hermes.flixari.co
    icon: https://assets.flixari.co/mailcow.png
    expectedStatusCodes:
      - 200
    maxRedirects: 0
  - name: 'Plex'
    url: https://plex.flixari.co/web/index.html
    icon: https://assets.flixari.co/apps/plex.png
    expectedStatusCodes:
      - 200
    maxRedirects: 0
  - name: Nextcloud
    url: https://cloud.flixari.co/login
    icon: https://assets.flixari.co/apps/nextcloud.png
    expectedStatusCodes:
      - 200
    maxRedirects: 0

assignees: # Users to assign downtime issues (optional)
  - SDS1337

status-website:
  cname: status.flixari.co
  publish: true
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Flixari - Uptime
  navbar:
    - title: Status
      href: /
    - title: Flixari
      href: https://flixari.co
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  links:
    - rel: stylesheet
      href: https://sds1337.github.io/css/upptime.css

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# EOF
