owner: SDS1337 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

assignees: # Users to assign downtime issues (optional)
  - SDS1337

status-website:
  cname: status.flixari.xyz
  publish: true
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Flixari - Upptime
  navbar:
    - title: Status
      href: /
    - title: Flixari
      href: https://flixari.xyz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  links:
    - rel: stylesheet
      href: https://sds1337.github.io/css/upptime.css
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
